Team-MOISAM/moisam-client

- src/app/index.css
- src/features/visited/ui/SecondStep.tsx
- src/pages/VisitedPage.tsx
- 배포환경에서 RE 페이지 스크롤 영역 수정
- X
- 배포 환경에서 RE 페이지 방문한 경우 두번째 스텝에서 스크롤 영역이 PC와 다르게 잡히는 문제를 해결하고자 합니다!
> [fix] 배포환경에서 RE 페이지 스크롤 영역 수정

- src/shared/utils/kakaoShare.ts
- KT2 이미지 비율 수정
- X
1. PC 카카오톡에서 우리의 공유하기가 안 예쁩니다... ㅜㅜ
> [fix] : KT2 이미지 비율 수정

- src/features/main/ui/KakaoLogin.tsx
> [fix] : 카카오 소셜 로그인 URI 수정

- src/pages/HistoryPage.tsx
- src/pages/MapViewPage.tsx
> [feat] : 링크로 들어온 사용차 처리

- src/features/main/ui/KakaoLogin.tsx
- src/features/mapView/ui/LoginModal.tsx
- src/shared/utils/index.ts
- src/shared/utils/kakaoLogin.ts
> [fix] : kakaoLogin utils 분리

- src/features/mapView/ui/BottomSheetContent.tsx
- src/shared/model/event.type.ts
> [feat] : 모임 생성자 추가 반영

- src/features/history/ui/Header.tsx
- src/features/mapView/config/subwayLine.ts
- src/features/mapView/ui/DetailBottomSheet/SubwayPath.tsx
- src/features/mapView/ui/MapDetailBottomSheet.tsx
- tailwind.config.cjs
- 지하철 노선 chip 구현
- 현재 배포 링크에서 바텀 시트가 잘리는 현상을 해결하고자 바텀시트 길이 조정하였습니다
- X
현재 서울을 중심으로 구현이 되었다보니 경춘선은 확인이 어려울 것 같습니다! 하지만 신분당선과 비슷하고 글자크기만 달라서 이상 없을 것 같습니다. 
- X
> [feat] : 지하철 노선 chip 구현

- src/features/my/ui/Profile.tsx
- MY 페이지 이름 수정 버튼 구현
- X
- 지금 로컬 환경에서 로그인을 할 수 없는 상황이라 우선 단순한 버튼 ui 구현이라 pr 올립니다!
> [feat] : MY 페이지 이름 수정 버튼 구현

- src/pages/HistoryPage.tsx
> [hotfix] : history 리다이렉트 수정

- src/features/mapView/ui/BottomSheetContent.tsx
- src/shared/ui/ShareModal.tsx
- Description 유무에 따라 구현을 달리 해보았습니다. 
- X
```
<ShareModal
onClose={() => setIsOpen(false)}
title="모임장소가 정해졌어요!"
description="멤버들에게 알려주세요"
shareContent={shareContent}
/>
```
- X
> [fix] : 디자인과 일치하지 않는 ui 수정

- src/features/my/hooks/useLogout.ts
- src/shared/stores/userStore.ts
- X
- persist 미들웨어를 사용하여 새로고침을 해도 정보들이 유지되도록 구현하였습니다. 유저의 개인정보에 해당하는 경우이므로 민감한 정보까지는 아닌데 개인 정보라 로컬 스토리지에 저장해도 되는가 ? 고민이 되는가 싶기는 합니다. 하지만 인증 정보나 단순 상태 관리를 위한 값들이라 로컬 스토리지에 저장해보았습니다. 이 부분과 관련해서는 다양한 피드백 주시면 좋을 것 같아요 😄  
https://surpise.tistory.com/9
> [fix] : zustand 새로고침 시 값 사라지는 문제 해결

- src/features/visited/ui/SecondStep.tsx
- src/pages/DetailPage.tsx
> [fix] : 스크롤 끝까지 안되는 문제 해결

- src/assets/icon/parking.svg
> [feat] : 주차장 표시 아이콘 변경

- src/features/history/hooks/index.ts
- src/features/history/hooks/useUserEvents.ts
- src/features/history/model/index.ts
- src/features/history/model/userEvents.type.ts
- src/features/history/service/api.ts
- src/features/history/ui/Chip.tsx
- src/features/history/ui/GroupCard.tsx
- src/pages/HistoryPage.tsx
> [feat] 유저 모임 리스트 get 요청 API 연결

- src/app/routes/routes.tsx
- src/features/mapView/ui/bottomsheets/SnapBottomSheet.tsx
- src/features/place/hooks/index.ts
- src/features/place/hooks/useRecommendedPlaces.ts
- src/features/place/model/placeList.type.ts
- src/features/place/service/api.ts
- src/features/place/service/index.ts
- src/features/place/ui/RecommendCard.tsx
- src/features/place/ui/RecommendList.tsx
- src/pages/PlacePage.tsx
- src/shared/model/mocks/mockPlaceItems.ts
- place페이지 api를 연결합니다.
x
- detail페이지로 넘어갈 때 경로 파라미터로 /detail/:eventId/:placeId의 형식으로 전달합니다.
> [feat] : place페이지 api 연결

- src/pages/DetailPage.tsx
- src/pages/HistoryPage.tsx
- src/pages/MapViewPage.tsx
- src/pages/PlacePage.tsx
- src/pages/ReviewPage.tsx
- src/shared/ui/LoadingSpinner.tsx
- src/shared/ui/ShareModal.tsx
- src/shared/ui/Toast.tsx
- src/shared/ui/index.ts
> [feat] : 로딩스피너 및 토스트팝업 구현

- src/features/mapView/ui/bottomsheets/MapDetailBottomSheet.tsx
- src/features/mapView/ui/map/DetailKakaoMapView.tsx
- src/features/mapView/ui/map/ParkingMarker.tsx
- src/pages/MapViewPage.tsx
- src/shared/model/event.type.ts
- X
주차장과 중간 지점 marker가 겹쳐지는 문제가 있습니다.. 우선 정확한 지점에 주차장 좌표를 찍는게 우선이라고 생각하여 찍어두기만 했습니다!
> [feat] : 자가용, 대중교통 상세 경로 표시

- jest.config.ts
- package.json
- pnpm-lock.yaml
- src/features/history/utils/formatDaysAgo.test.ts
- src/features/history/utils/formatDaysAgo.ts
- src/shared/utils/toValidScore.test.ts
- tsconfig.app.json
- tsconfig.json
- x
- pnpm test 입력 시
- 우선 typescript 관련하여 test 진행하기에 간단히 세팅하였습니다.
> [feat] : jest 테스트 함수 구현

- src/shared/utils/formatReview.test.ts
- src/shared/utils/validateName.test.ts
- validateName.ts 테스트코드 작성
- formatReview.ts 테스트 코드 작성
x
> [feat] : validateName 및 formatReview 테스트 코드 작성

- src/shared/utils/kakaoShare.ts
- 카카오 공유가 실패할 경우 alert를 띄웁니다.
x
> [feat] : kt 에러 핸들링 추가

- index.html
- clarity 스크립트 추가
- google analytics 스크립트 추가
> [feat] : ms clarity 및 google analytics 스크립트 추가

- index.html
- package.json
- pnpm-lock.yaml
- src/app/App.tsx
- src/pages/DetailPage.tsx
- src/pages/HistoryPage.tsx
- src/pages/MapViewPage.tsx
- src/pages/MyPage.tsx
- src/pages/NotVisitedPage.tsx
- src/pages/PlacePage.tsx
- src/pages/ReviewPage.tsx
- src/pages/VisitedPage.tsx
- X
- 아래의 사진처럼 title 변경되도록 적용했습니다
> [feat] : react-helmet-async 적용

- package.json
- pnpm-lock.yaml
- src/app/App.tsx
- 페이지뷰, 로딩 성능, Core Web Vitals 등 성능 추적을 위한 vercel analytics를 연결합니다.
- 질문 작성
> [SPOT-90] : vercel analytics 연결

- src/pages/MainPage.tsx
- src/shared/api/api.ts
- src/shared/utils/kakaoLogin.ts
> [feat] : main에 병합

- index.html
- src/features/my/ui/Menu.tsx
- src/shared/api/api.ts
- src/shared/utils/kakaoLogin.ts
> [feat]: dev 최신화

- src/widgets/headers/ui/MapHeader.tsx
> [MOISAM-196] : MP 헤더 상위로 노출

- src/pages/HistoryPage.tsx
- 현재 HI 페이지에서 리뷰를 작성할 수 있으면 리뷰 페이지 로직으로 진입하는 로직을 제거합니다. 
- X
- 해당 부분은 실제 dev 머지 후 확인이 필요합니다.
> [MOISAM-212] : 리뷰 재진입 로직 제거

- src/features/history/ui/GroupCard.tsx
- HI 페이지에서 모임 참여 인원이 1명일 경우 중간 지점 역 표시를 제거합니다. 
- X
- DEV로 머지 후 HI 페이지 확인이 필요합니다.
> [MOISAM-213] : HI 1명일 경우 역 제거
